nome = input("Qual seu nome")
idade = int(input("Qual seu idade"))
telefone = input("qual seu telefone")
cpf = input("Qual seu cpf")
estado_civil = input("Qual seu estado civil")
genero = input("Qual seu genero")
altura = float(input("Qual sua altura"))

print("-" * 25)
print(f"Nome da pessoa: {nome} ")
print(f"Idade da pessoa: {idade}")
print(f"Telelfone da pessoa: {telefone}")
print(f"Cpf da pessoa: {cpf}")
print(f"Estado civil da pessoa: {estado_civil}")
print(f"Genero da pessoa: {genero}")
print("Altura da pessoa", altura)
print("-" * 25)